import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Skeleton } from "@/components/ui/skeleton";
import { useSpeakers } from "@/hooks/use-speakers";
import { formatDateJST } from "@/lib/date";

export function SpeakerAssignPanel() {
  const { speakers, loading, error, renameSpeaker, deleteSpeaker } = useSpeakers();
  const [editingName, setEditingName] = useState<string | null>(null);
  const [nameInput, setNameInput] = useState("");
  const [pendingAction, setPendingAction] = useState<string | null>(null);

  const handleStartEdit = (name: string) => {
    setEditingName(name);
    setNameInput(name);
  };

  const handleCancelEdit = () => {
    setEditingName(null);
    setNameInput("");
  };

  const handleRename = async (oldName: string) => {
    const newName = nameInput.trim();
    if (!newName || newName === oldName) {
      handleCancelEdit();
      return;
    }
    setPendingAction(oldName);
    try {
      await renameSpeaker(oldName, newName);
      handleCancelEdit();
    } finally {
      setPendingAction(null);
    }
  };

  const handleDelete = async (name: string) => {
    setPendingAction(name);
    try {
      await deleteSpeaker(name);
    } finally {
      setPendingAction(null);
    }
  };

  if (loading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Speakers</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          {["skeleton-1", "skeleton-2"].map((id) => (
            <Skeleton key={id} className="h-24 w-full" />
          ))}
        </CardContent>
      </Card>
    );
  }

  if (error) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Speakers</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground">{error}</p>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>
          Speakers
          <Badge variant="secondary" className="ml-2">
            {speakers.length}
          </Badge>
        </CardTitle>
      </CardHeader>
      <CardContent>
        {speakers.length === 0 ? (
          <p className="text-sm text-muted-foreground">No speakers registered.</p>
        ) : (
          <ScrollArea className="h-[400px]">
            <div className="space-y-4">
              {speakers.map((speaker) => (
                <div
                  key={speaker.name}
                  className={`rounded-md border p-3 ${speaker.autoGenerated ? "border-yellow-500/30 bg-yellow-50/50 dark:bg-yellow-950/10" : ""}`}
                >
                  <div className="mb-2 flex items-center gap-2">
                    {editingName === speaker.name ? (
                      <Input
                        value={nameInput}
                        onChange={(e) => setNameInput(e.target.value)}
                        onKeyDown={(e) => {
                          if (e.key === "Enter") handleRename(speaker.name);
                          if (e.key === "Escape") handleCancelEdit();
                        }}
                        className="h-7 text-sm font-medium"
                        disabled={pendingAction === speaker.name}
                        autoFocus
                      />
                    ) : (
                      <span className="text-sm font-medium">{speaker.name}</span>
                    )}
                    {speaker.autoGenerated && (
                      <Badge variant="outline" className="text-yellow-600">
                        auto
                      </Badge>
                    )}
                    <Badge variant="outline">{speaker.occurrenceCount}x</Badge>
                    {speaker.firstSeen && speaker.lastSeen && (
                      <span className="ml-auto text-xs text-muted-foreground">
                        {formatDateJST(speaker.firstSeen)} - {formatDateJST(speaker.lastSeen)}
                      </span>
                    )}
                  </div>
                  {speaker.sampleTexts.length > 0 && (
                    <div className="mb-3 space-y-1">
                      {speaker.sampleTexts.slice(0, 3).map((text) => (
                        <p key={text} className="line-clamp-1 text-xs text-muted-foreground">
                          "{text}"
                        </p>
                      ))}
                    </div>
                  )}
                  <div className="flex items-center gap-2">
                    {editingName === speaker.name ? (
                      <>
                        <Button
                          size="sm"
                          onClick={() => handleRename(speaker.name)}
                          disabled={
                            !nameInput.trim() ||
                            nameInput.trim() === speaker.name ||
                            pendingAction === speaker.name
                          }
                        >
                          Save
                        </Button>
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={handleCancelEdit}
                          disabled={pendingAction === speaker.name}
                        >
                          Cancel
                        </Button>
                      </>
                    ) : (
                      <>
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => handleStartEdit(speaker.name)}
                          disabled={pendingAction === speaker.name}
                        >
                          Rename
                        </Button>
                        <Button
                          size="sm"
                          variant="destructive"
                          onClick={() => handleDelete(speaker.name)}
                          disabled={pendingAction === speaker.name}
                        >
                          Delete
                        </Button>
                      </>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </ScrollArea>
        )}
      </CardContent>
    </Card>
  );
}
