import { useCallback, useEffect, useState } from "react";
import { deleteAdasApi, fetchAdasApi, postAdasApi } from "./use-adas-api";

export interface SpeakerSummary {
  name: string;
  autoGenerated: boolean;
  firstSeen: string | null;
  lastSeen: string | null;
  sampleTexts: string[];
  occurrenceCount: number;
  hasEmbedding: boolean;
}

export function useSpeakers() {
  const [speakers, setSpeakers] = useState<SpeakerSummary[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  const fetchSpeakers = useCallback(async (silent = false) => {
    try {
      if (!silent) setLoading(true);
      const data = await fetchAdasApi<SpeakerSummary[]>("/api/speakers");
      setSpeakers(data);
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to fetch speakers");
    } finally {
      if (!silent) setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchSpeakers();
    const interval = setInterval(() => fetchSpeakers(true), 30_000);
    return () => clearInterval(interval);
  }, [fetchSpeakers]);

  const renameSpeaker = useCallback(
    async (oldName: string, newName: string) => {
      await postAdasApi("/api/speakers/rename", { oldName, newName });
      await fetchSpeakers(true);
    },
    [fetchSpeakers],
  );

  const deleteSpeaker = useCallback(
    async (name: string) => {
      await deleteAdasApi(`/api/speakers/${encodeURIComponent(name)}`);
      await fetchSpeakers(true);
    },
    [fetchSpeakers],
  );

  return { speakers, error, loading, refetch: fetchSpeakers, renameSpeaker, deleteSpeaker };
}
